import { create } from 'zustand';

// Zustand is the standard for React-Three-Fiber state management 
// because it prevents unnecessary re-renders of the 3D canvas.
// If you haven't installed it yet, run: npm install zustand

const useDesignStore = create((set) => ({
  // --- State ---
  walls: [],
  furniture: [],
  activeItem: null, // Tracks which furniture piece is currently selected

  // --- Actions ---
  
  // 1. Set the walls generated by the AI backend
  setWalls: (newWalls) => set({ walls: newWalls }),

  // 2. Add a new furniture item to the room
  addFurniture: (item) => set((state) => ({ 
    furniture: [...state.furniture, { ...item, id: Date.now().toString() }] 
  })),

  // 3. Update position when dragging an item
  updateFurniturePosition: (id, newPosition) => set((state) => ({
    furniture: state.furniture.map((item) => 
      item.id === id ? { ...item, position: newPosition } : item
    )
  })),

  // 4. Update rotation when rotating an item
  updateFurnitureRotation: (id, newRotation) => set((state) => ({
    furniture: state.furniture.map((item) => 
      item.id === id ? { ...item, rotation: newRotation } : item
    )
  })),

  // 5. Remove an item from the room
  removeFurniture: (id) => set((state) => ({
    furniture: state.furniture.filter((item) => item.id !== id),
    activeItem: state.activeItem === id ? null : state.activeItem
  })),

  // 6. Set the currently selected item
  setActiveItem: (id) => set({ activeItem: id }),

  // 7. Clear the entire workspace
  clearDesign: () => set({ walls: [], furniture: [], activeItem: null })
}));

export default useDesignStore